networks:
  dev:

services:

  nginx:
    image: nginx:alpine
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - dev



  backend:
    build:
      context: ./backend
    networks:
      - dev

  frontend:
    build:
      context: frontend
    networks:
      - dev
